# -------------------------------------------------------------------------------------------
#
#  Welcome to DeathWarden's main configuration file.
#
#  Here you'll find of the settings and options that you can
#  customize to your server needs. Most features are customizable
#  to an extent.
#
#  You can find all the potion effects here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/potion/PotionEffectType.html
#
# -------------------------------------------------------------------------------------------

# If true, All pvp related deaths will be logged in the log.yml file
Log_PvP_Deaths: true

# If true, OmegaDeath will keep record of all player deaths and store it in the playerData.yml.
# Players who have the permission `omegadeath.deathcount` will be able to use the command
# `/deathcount` to view how many times they have died.
Death_Counter: true

# If true, OmegaDeath with keep record of all the pvp kills that a player makes and will store it in the playerData.yml
# Players who have the permission `omegadeath.pvpkills` will be able use the command
# `/pvpkills` to view how many times they have killed another player.
PvP_Kill_Counter: true

# If true, a message will sent to all players online when someone dies.
Death_Messages: true

# If true, A special message will be sent to the player who got killed by another player
Death_By_Player_Messages: true

# Should players retain their death effect status when they login/logout
Death_Effects_Login: true

# Should players retain their death effect status when the server restarts
Death_Effects_Restart: true

# Whether the player should be penalised for not having the money to pay when they die
Death_Penalty: true

# Set this to false if you want another plugin to handle the /back command
Register_Back_Command: true

# Set the default death effects that all players will get when they join the server
# The timer/duration is in seconds.
# Use the permission `deathwarden.deatheffects.default.exempt` to be exempt from receiving them
Default_Death_Effects:
  # Whether you're wanting to use death death effects
  Enabled: false
  # The specific default death effects you want to use.
  Effects:
    Particle: "EXPLOSION_NORMAL"
    Sound: "ENTITY_CAT_DEATH"

# Sets a potion effect the player recieves when they don't have enough money for the death tax
# Requires Death_Penalty to be set to true
Death_Penalty_Effect:
  # The potion effects to apply
  # The Timer is in seconds
  Potion_Effect:
    WEAKNESS:
      Amplifier: 1
      Timer: 10
    CONFUSION:
      Amplifier: 1
      Timer: 10
    SLOW:
      Amplifier: 1
      Timer: 10

# Sets a potion effect the player recieves when they don't have enough money to pay for death tax
# Requires Death_Penalty to be set to true
Kill_Penalty_Effect:
  # The potion effects to apply
  # The Timer is in seconds
  Potion_Effect:
    WEAKNESS:
      Amplifier: 1
      Timer: 10
    CONFUSION:
      Amplifier: 1
      Timer: 10
    SLOW:
      Amplifier: 1
      Timer: 10

# Sets the amount of money that gets taken from the users account when they die.
# You can use either a percentage or an exact amount to be taken
Death_Tax:
  Percentage:
    # Take a percentage of the players money when they die.
    Enabled: false
    # The percentage amount to be taken
    Amount: 10.00
  Exact_Amount:
    # Take an exact amount from the player money when they die.
    Enabled: true
    # The exact amount to be taken
    Amount: 10.00

# Sets the amount of money that gets taken from the users account when they kill another player
# You can use either a percentage or an exact amount
Kill_Tax:
  Percentage:
    # Take a percentage of the players money when they kill another player
    Enabled: false
    # The percentage amount to the taken
    Amount: 10.00
  Exact_Amount:
    # Take an exact amount from the players money when they kill another player
    Enabled: true
    Amount: 10.00

# Set custom commands that are run when a player dies
# All the commands will be run through console.
# Use %player% to get the players name & %killer% to get the player who did the killing
# This is triggered when a player is killed by another player.
Death_Commands:
  Enabled: true
  Commands:
    - eco take %player% 10

# This is triggered when a player respawns.
Respawn_Commands:
  Enabled: true
  Commands:
    - spawn %player%

# This is triggered when a player kills another player.
Kill_Commands:
  Enabled: true
  Commands:
    - eco give %killer% 10
    - eco take %player% 10

# This is triggered when the player is killed by anything other than a player
Death_By_NonPlayer:
  Enabled: true
  Commands:
    - eco take %player% 10

# The list of worlds that death effects will be disabled in.
# All Death Effects, totals, logging and rewards will be disabled for the worlds.
Disabled_Worlds:
  Enabled: true
  Worlds:
    - world_the_end
    - world_nether

# Which time-format the time stamp in the log.yml will be displayed in
# Options are: AUS (dd.mm.yyy hh:mm:ss) OR US (mm.dd.yyyy hh:mm:ss) OR CHN (yyyy.mm.dd hh:mm:ss)
# Defaults to AUS if option is invalid
Time_Format: AUS

# If set to true, those with the permission deathwarden.update will recieve messages
# when the plugin updates on spigot
Update_Notify: true

# DO NOT EDIT THIS!
Config_Version: 2.4